Repository pknu-wap/WABI-FE, pull requests merged in 2024-11, with the labels that each got.

#92 [feature] 관리자 로그인, 회원가입 UI 제작
  client/src/App.tsx
  client/src/components/Authentication/SignInForm/SignInForm.styles.ts
  client/src/components/Authentication/SignInForm/SignInForm.tsx
  client/src/components/Authentication/SignUpForm/SignUpForm.styles.ts
  client/src/components/Authentication/SignUpForm/SignUpForm.tsx
  client/src/components/common/CommonFormLayout/CommonFormLayout.styles.ts
  client/src/components/common/CommonFormLayout/CommonFormLayout.tsx
  client/src/pages/SignIn/SignIn.styles.ts
  client/src/pages/SignIn/SignIn.tsx
  client/src/pages/SignUp/SignUp.styles.ts
  client/src/pages/SignUp/SignUp.tsx
Labels: feature, 딜런

#94 [refactor] React Query 도입 및 이벤트/체크인 관련 컴포넌트 리팩토링
  client/package-lock.json
  client/package.json
  client/src/api/event.ts
  client/src/api/loadCheckInList.ts
  client/src/api/loadEventList.ts
  client/src/api/loadGroupList.ts
  client/src/components/EventAndGroupList/CreateEventForm/CreateEventForm.tsx
  client/src/components/EventAndGroupList/EventCardList/EventCardList.tsx
  client/src/components/common/Title/Title.tsx
  client/src/components/event_detail/CheckInStatus/CheckInStatus.tsx
  client/src/components/event_detail/CheckInTable/CheckInTable.tsx
  client/src/constants/config.txt
  client/src/constants/queryKeys.ts
  client/src/hooks/useCheckInStudent.tsx
  client/src/index.tsx
  client/src/pages/EventDetail/EventDetail.tsx
  client/src/queries/eventQueries/useCreateEvent.ts
  client/src/queries/eventQueries/useDeleteEvent.ts
  client/src/queries/eventQueries/useGetCheckInList.ts
  client/src/queries/eventQueries/useGetEvent.ts
  client/src/queries/eventQueries/useGetEventList.ts
  client/src/queries/eventQueries/useUpdateEvent.ts
  client/src/utils/convertToKoreanTime.ts
Labels: feature, 하키, 딜런, fix

#95 파비콘 및 로고 수정, index.html 메타 태그 개선
  client/public/favicon.ico
  client/public/images/wabi.png
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/og-image.png
Labels: feature, 딜런

#98 [refactor] 에러 시 QR 재인식 안되는 문제
  client/src/api/sendToServer.ts
  client/src/components/QrCheckIn/QrScan.tsx
  client/src/utils/resetQrScanner.ts
Labels: 하키, refactor

#102 [fix] 정상 참석 시 딜레이 추가
  client/src/components/QrCheckIn/QrScan.tsx
Labels: 하키, fix
