Repository pknu-wap/WABI-FE, pull requests merged in 2024-09, with the labels that each got.

#12 서버에서 이벤트,시간,학번,이름 가져오기 및 qr페이지 low-fi 제작
  client/src/App.tsx
  client/src/api/LoadCheckInStudent.ts
  client/src/api/SendToServer.ts
  client/src/constants/con.txt
  client/src/constants/config.txt
  client/src/hooks/con.txt
  client/src/hooks/config.txt
  client/src/pages/QrCheckIn/MainQrCheckIn.tsx
  client/src/pages/QrCheckIn/QrCheckIn.styles.ts
  client/src/pages/QrCheckIn/QrScan.tsx
  client/src/pages/QrScan/QrScan.tsx
  client/src/pages/main_qr_check_in/MainQrCheckIn.tsx
  client/src/pages/main_qr_check_in/QrScan.tsx
  client/src/types/QrType/ScanData.ts
  client/src/types/QrType/StudentQr.ts
  client/src/types/types.txt
Labels: feature, 하키, 퓨어

#11 group_detail lo-fi UI 제작
  client/.prettierrc
  client/eslint.config.mjs
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/api/fileUpload.ts
  client/src/api/manualUpload.ts
  client/src/components/com.txt
  client/src/components/common/Button/Button.styles.ts
  client/src/components/common/Button/Button.tsx
  client/src/components/common/Header/Header.styles.ts
  client/src/components/common/Header/Header.tsx
  client/src/components/common/Logo/Logo.styles.ts
  client/src/components/common/Logo/Logo.tsx
  client/src/components/common/ModalFrame/ModalFrame.styles.ts
  client/src/components/common/ModalFrame/ModalFrame.tsx
  client/src/components/group_detail/FileUploadModal/FileUploadModal.tsx
  client/src/components/group_detail/ManualUploadModal/ManualUploadModal.tsx
  client/src/components/group_detail/MemberUpdateButton/MemberUpdateButton.tsx
  client/src/icon.png
  client/src/index.tsx
  client/src/pages/GroupDetail/GroupDetail.tsx
  client/src/recoil/modalState.ts
  client/src/recoil/recoil.txt
  client/tsconfig.json
Labels: feature, 마이크, 딜런

#18 QR재인식 및 카메라 좌우반전
  client/src/pages/QrCheckIn/MainQrCheckIn.styles.ts
  client/src/pages/QrCheckIn/MainQrCheckIn.tsx
  client/src/pages/QrCheckIn/QrScan.tsx
  client/src/pages/QrCheckIn/qrCode.styles.ts
  client/src/pages/main_qr_check_in/MainQrCheckIn.tsx
  client/src/pages/main_qr_check_in/QrScan.tsx
Labels: feature, 하키, 퓨어

#19 체크인 현황 페이지 제작
  .idea/workspace.xml
  client/src/api/LoadCheckInStudent.ts
  client/src/api/SendToServer.ts
  client/src/components/QrCheckIn/QrScan.tsx
  client/src/components/QrCheckIn/qrCode.styles.ts
  client/src/components/event_detail/CheckInTable/CheckInTable.styles.ts
  client/src/components/event_detail/CheckInTable/CheckInTable.tsx
  client/src/hooks/useCheckInStudent.tsx
  client/src/pages/EventDetail/EventDetail.tsx
  client/src/pages/QrCheckIn/MainQrCheckIn.styles.ts
  client/src/pages/QrCheckIn/MainQrCheckIn.tsx
Labels: feature, 하키

#14 group_detail 페이지에서 그룹 인원 리스트 컴포넌트 생성
  client/src/api/loadGroupMemberList.ts
  client/src/components/GroupDetail/FileUploadModal/FileUploadModal.tsx
  client/src/components/GroupDetail/ManualUploadModal/ManualUploadModal.tsx
  client/src/components/GroupDetail/ManualUploadModal/steps/OptionalStep.tsx
  client/src/components/GroupDetail/ManualUploadModal/steps/RequiredStep.tsx
  client/src/components/GroupDetail/ManualUploadModal/steps/Steps.tsx
  client/src/components/GroupDetail/MemberUpdateButton/MemberUpdateButton.tsx
  client/src/components/common/GroupMemberList/GroupMember.tsx
  client/src/components/common/GroupMemberList/GroupMemberList.styles.ts
  client/src/components/common/GroupMemberList/GroupMemberList.tsx
  client/src/components/common/GroupMemberList/GroupMembers.tsx
  client/src/pages/GroupDetail/GroupDetail.tsx
Labels: feature, 하키, 마이크, 딜런

#24 Main_qr_check_in 페이지 UI 구현
  client/src/App.css
  client/src/App.tsx
  client/src/api/SendToServer.ts
  client/src/components/QrCheckIn/QrScan.tsx
  client/src/pages/QrCheckIn/MainQrCheckIn.styles.ts
  client/src/pages/QrCheckIn/MainQrCheckIn.tsx
Labels: feature, 퓨어

#26 [feature] event_list 임시 페이지와 Routing 기능 추가
  client/package-lock.json
  client/package.json
  client/public/images/checkInDot.png
  client/public/images/notCheckInDot.png
  client/public/images/qrCheckInButton.png
  client/src/App.tsx
  client/src/components/common/Header/Header.styles.ts
  client/src/components/common/SearchAndButtonFrame/SearchAndButtonFrame.styles.ts
  client/src/components/common/SearchAndButtonFrame/SearchAndButtonFrame.tsx
  client/src/components/event_detail/CheckInTable/CheckInTable.styles.ts
  client/src/components/event_detail/CheckInTable/CheckInTable.tsx
  client/src/pages/EventDetail/EventDetail.styles.ts
  client/src/pages/EventDetail/EventDetail.tsx
  client/src/pages/QrCheckIn/MainQrCheckIn.tsx
Labels: feature, 마이크

#27 [release] v0.1.0 배포
  .idea/workspace.xml
  client/.prettierrc
  client/eslint.config.mjs
  client/package-lock.json
  client/package.json
  client/public/images/checkInDot.png
  client/public/images/notCheckInDot.png
  client/public/images/qrCheckInButton.png
  client/src/App.css
  client/src/App.tsx
  client/src/api/fileUpload.ts
  client/src/api/loadGroupMemberList.ts
  client/src/api/manualUpload.ts
  client/src/api/sendToServer.ts
  client/src/components/GroupDetail/FileUploadModal/FileUploadModal.tsx
  client/src/components/GroupDetail/ManualUploadModal/ManualUploadModal.tsx
  client/src/components/GroupDetail/ManualUploadModal/steps/OptionalStep.tsx
  client/src/components/GroupDetail/ManualUploadModal/steps/RequiredStep.tsx
  client/src/components/GroupDetail/ManualUploadModal/steps/Steps.tsx
  client/src/components/GroupDetail/MemberUpdateButton/MemberUpdateButton.tsx
  client/src/components/QrCheckIn/QrScan.tsx
  client/src/components/QrCheckIn/qrCode.styles.ts
  client/src/components/common/Button/Button.styles.ts
  client/src/components/common/Button/Button.tsx
  client/src/components/common/GroupMemberList/GroupMember.tsx
  client/src/components/common/GroupMemberList/GroupMemberList.styles.ts
  client/src/components/common/GroupMemberList/GroupMemberList.tsx
  client/src/components/common/GroupMemberList/GroupMembers.tsx
  client/src/components/common/Header/Header.styles.ts
  client/src/components/common/Header/Header.tsx
  client/src/components/common/Logo/Logo.styles.ts
  client/src/components/common/Logo/Logo.tsx
  client/src/components/common/ModalFrame/ModalFrame.styles.ts
  client/src/components/common/ModalFrame/ModalFrame.tsx
  client/src/components/common/SearchAndButtonFrame/SearchAndButtonFrame.styles.ts
  client/src/components/common/SearchAndButtonFrame/SearchAndButtonFrame.tsx
  client/src/components/event_detail/CheckInTable/CheckInTable.styles.ts
  client/src/components/event_detail/CheckInTable/CheckInTable.tsx
  client/src/constants/config.txt
  client/src/hooks/config.txt
  client/src/hooks/useCheckInStudent.tsx
  client/src/icon.png
  client/src/index.tsx
  client/src/pages/EventDetail/EventDetail.styles.ts
  client/src/pages/EventDetail/EventDetail.tsx
  client/src/pages/GroupDetail/GroupDetail.tsx
  client/src/pages/QrCheckIn/MainQrCheckIn.styles.ts
  client/src/pages/QrCheckIn/MainQrCheckIn.tsx
  client/src/react-qr-scanner.d.ts
  client/src/recoil/modalState.ts
  client/src/types/QrType/ScanData.ts
  client/src/types/QrType/StudentQr.ts
  client/src/types/stepTypes.ts
  client/src/types/studentTypes.ts
  client/tsconfig.json
Labels: 마이크, release

#28 [feature] 배포 branch master 에서 해놓은 hotfix 모두 develop에 적용
  .github/pull_request_template.md
  client/netlify.toml
  client/package.json
  client/public/_redirects
  client/src/components/GroupDetail/ManualUploadModal/steps/Steps.tsx
  client/src/components/QrCheckIn/QrScan.tsx
  client/src/components/common/Button/Button.tsx
  client/src/hooks/useCheckInStudent.tsx
  client/src/pages/EventDetail/EventDetail.tsx
Labels: hotfix, 마이크

#29 [release] v0.1.1 배포
  client/src/api/sendToServer.ts
  client/src/hooks/useCheckInStudent.tsx
Labels: 마이크, release

#30 [release] v0.1.2 배포
  client/src/App.tsx
  client/src/components/event_detail/CheckInTable/CheckInTable.tsx
  client/src/pages/EventDetail/EventDetail.tsx
  client/src/pages/MainEventList/MainEventList.tsx
Labels: 마이크, release

#32 체크인현황 테이블 key변경
  client/src/components/event_detail/CheckInTable/CheckInTable.tsx
Labels: feature, 하키

#35 [feature] 이벤트/그룹 개설을 위한 공용 폼 및 관련 컴포넌트 제작
  client/public/images/Icon/DeleteButtonIcon.png
  client/src/App.tsx
  client/src/components/EventGroupSwitcher/CreateEventForm/CreateEventForm.tsx
  client/src/components/EventGroupSwitcher/CreateGroupForm/CreateGroupForm.tsx
  client/src/components/common/Button/Button.tsx
  client/src/components/common/CommonFormLayout/CommonFormLayout.styles.ts
  client/src/components/common/CommonFormLayout/CommonFormLayout.tsx
  client/src/components/common/InputField/InputField.styles.ts
  client/src/components/common/InputField/InputField.tsx
  client/src/pages/EventGroupSwitcher/EventGroupSwitcher.tsx
Labels: feature, 딜런

#36 [feature] 메인 이벤트 리스트를 위한 컴포넌트 제작
  client/public/images/EditEvent.png
  client/src/components/EventGroupSwitcher/EventCard/EventCard.styles.ts
  client/src/components/EventGroupSwitcher/EventCard/EventCard.tsx
  client/src/components/EventGroupSwitcher/EventCard/ParticipateProgress/ParticipateProgress.styles.ts
  client/src/components/EventGroupSwitcher/EventCard/ParticipateProgress/ParticipateProgress.tsx
  client/src/components/EventGroupSwitcher/EventCardList/EventCardList.styles.ts
  client/src/components/EventGroupSwitcher/EventCardList/EventCardList.tsx
Labels: feature, 하키

#42 [feature] 이벤트/그룹 생성 폼 스타일 적용
  client/src/components/EventGroupSwitcher/CreateEventForm/CreateEventForm.tsx
  client/src/components/EventGroupSwitcher/CreateGroupForm/CreateGroupForm.tsx
  client/src/components/EventGroupSwitcher/FormSaveButton/FormSaveButton.styles.ts
  client/src/components/EventGroupSwitcher/FormSaveButton/FormSaveButton.tsx
  client/src/components/common/Button/Button.styles.ts
  client/src/components/common/Button/Button.tsx
  client/src/components/common/CommonFormLayout/CommonFormLayout.styles.ts
  client/src/components/common/CommonFormLayout/CommonFormLayout.tsx
  client/src/components/common/InputField/InputField.styles.ts
  client/src/components/common/InputField/InputField.tsx
Labels: feature, 딜런

#48 [feature] 이벤트 생성, 수정, 삭제 기능 API 연동 완료
  client/src/api/event.ts
  client/src/components/EventGroupSwitcher/CreateEventForm/CreateEventForm.tsx
  client/src/components/common/CommonFormLayout/CommonFormLayout.tsx
  client/src/components/common/InputField/InputField.tsx
  client/src/types/eventTypes.ts
Labels: feature, 딜런

#47 [bugfix] 메인 QR 체크인 페이지와 헤더 UI 개선
  client/public/images/eventIcon.png
  client/public/images/user.png
  client/public/images/wabi.png
  client/src/components/QrCheckIn/QrScan.tsx
  client/src/components/QrCheckIn/qrCode.styles.ts
  client/src/components/common/Button/Button.styles.ts
  client/src/components/common/Header/Header.styles.ts
  client/src/components/common/Header/Header.tsx
  client/src/components/common/Logo/Logo.styles.ts
  client/src/components/common/Logo/Logo.tsx
  client/src/components/common/ModalFrame/ModalFrame.tsx
  client/src/pages/QrCheckIn/MainQrCheckIn.styles.ts
  client/src/pages/QrCheckIn/MainQrCheckIn.tsx
Labels: bugfix, 퓨어

#52 [feature] EventDetail 페이지 UI 구성 및 Title 공통 컴포넌트 생성
  client/public/images/Icon/qrCheckInIcon.png
  client/public/images/Icon/searchIcon.png
  client/src/App.tsx
  client/src/components/QrCheckIn/QrScan.tsx
  client/src/components/common/SearchAndButtonFrame/SearchAndButtonFrame.tsx
  client/src/components/common/SearchBox/SearchBox.styles.ts
  client/src/components/common/SearchBox/SearchBox.tsx
  client/src/components/common/Title/Title.styles.ts
  client/src/components/common/Title/Title.tsx
  client/src/components/event_detail/CheckInGroup/CheckInGroup.styles.ts
  client/src/components/event_detail/CheckInGroup/CheckInGroup.tsx
  client/src/components/event_detail/CheckInTable/CheckInTable.styles.ts
  client/src/components/event_detail/CheckInTable/CheckInTable.tsx
  client/src/components/event_detail/GroupCard/GroupCard.styles.ts
  client/src/components/event_detail/GroupCard/GroupCard.tsx
  client/src/hooks/useCheckInEvent.tsx
  client/src/hooks/useCheckInStudent.tsx
  client/src/pages/EventDetail/EventDetail.styles.ts
  client/src/pages/EventDetail/EventDetail.tsx
  client/src/pages/GroupDetail/GroupDetail.tsx
  client/src/pages/QrCheckIn/MainQrCheckIn.tsx
Labels: feature, 마이크

#54 [feature] 그룹 생성, 수정, 삭제 기능 API 연동 완료
  client/src/api/group.ts
  client/src/components/EventGroupSwitcher/CreateEventForm/CreateEventForm.tsx
  client/src/components/EventGroupSwitcher/CreateGroupForm/CreateGroupForm.tsx
  client/src/pages/EventGroupSwitcher/EventGroupSwitcher.tsx
  client/src/types/eventTypes.ts
  client/src/types/groupTypes.ts
Labels: feature, 딜런

#55 [feture] 이벤트, 그룹 리스트와 수정폼 합치기
  client/src/api/loadGroupList.tsx
  client/src/components/EventGroupSwitcher/EventCard/EventCard.styles.ts
  client/src/components/EventGroupSwitcher/EventCard/EventCard.tsx
  client/src/components/EventGroupSwitcher/EventCard/ParticipateProgress/ParticipateProgress.styles.ts
  client/src/components/EventGroupSwitcher/EventCardList/EventCardList.styles.ts
  client/src/components/EventGroupSwitcher/EventGroup/GroupCard.styles.ts
  client/src/components/EventGroupSwitcher/EventGroup/GroupCard.tsx
  client/src/components/EventGroupSwitcher/EventGroupList/EventGroupList.styles.ts
  client/src/components/common/CommonFormLayout/CommonFormLayout.styles.ts
  client/src/pages/EventGroupSwitcher/EventGroupSwitcher.styles.ts
  client/src/pages/EventGroupSwitcher/EventGroupSwitcher.tsx
  client/src/recoil/currentBandId.ts
  client/src/recoil/currentEventId.ts
Labels: feature, 하키

#57 [hotfix] Band 타입 임포트 및 eventId 타입 수정
  client/src/api/loadGroupList.tsx
  client/src/components/EventGroupSwitcher/EventCard/EventCard.tsx
  client/src/components/EventGroupSwitcher/EventGroup/GroupCard.tsx
  client/src/recoil/currentEventId.ts
Labels: hotfix, 하키

#58 [feature] EventGroupSwitcher: 이벤트/그룹 탭 전환 구현 완료
  client/src/components/EventGroupSwitcher/ToggleTabs/TabSwitcher.styles.ts
  client/src/components/EventGroupSwitcher/ToggleTabs/TabSwitcher.tsx
  client/src/pages/EventGroupSwitcher/EventGroupSwitcher.styles.ts
  client/src/pages/EventGroupSwitcher/EventGroupSwitcher.tsx
Labels: feature, 딜런

#60 [feature] Event Detail 페이지 Event 이름 및 그룹 리스트 받아오기
  client/src/components/common/Title/Title.tsx
  client/src/components/event_detail/CheckInGroup/CheckInGroup.tsx
  client/src/components/event_detail/CheckInStatus/CheckInStatus.styles.ts
  client/src/components/event_detail/CheckInStatus/CheckInStatus.tsx
  client/src/components/event_detail/CheckInTable/CheckInTable.tsx
  client/src/hooks/useCheckInStudent.tsx
  client/src/pages/EventDetail/EventDetail.styles.ts
  client/src/pages/EventDetail/EventDetail.tsx
  client/src/types/eventTypes.ts
Labels: feature, 마이크

#63 [Hotfix] merge 이후 import 경로 오류 해결
  client/src/components/EventGroupSwitcher/EventGroupList/EventGroupList.tsx
  client/src/components/EventGroupSwitcher/GroupCard/GroupCard.styles.ts
  client/src/components/EventGroupSwitcher/GroupCard/GroupCard.tsx
  client/src/components/event_detail/CheckInGroup/CheckInGroup.tsx
  client/src/pages/EventDetail/EventDetail.tsx
  client/src/pages/EventGroupSwitcher/EventGroupSwitcher.tsx
Labels: bugfix, 딜런

#64 [feature] 이벤트 카드 프로그래스바 제작
  client/src/api/loadEventList.tsx
  client/src/components/EventGroupSwitcher/EventCard/EventCard.styles.ts
  client/src/components/EventGroupSwitcher/EventCard/EventCard.tsx
  client/src/components/EventGroupSwitcher/EventCard/ParticipateProgress/ParticipateProgress.styles.ts
  client/src/components/EventGroupSwitcher/EventCard/ParticipateProgress/ParticipateProgress.tsx
  client/src/components/EventGroupSwitcher/EventGroupList/EventGroupList.styles.ts
  client/src/components/EventGroupSwitcher/GroupCard/GroupCard.styles.ts
  client/src/components/EventGroupSwitcher/GroupCard/GroupCard.tsx
  client/src/components/EventGroupSwitcher/ParticipateProgress/ParticipateProgress.styles.ts
  client/src/components/EventGroupSwitcher/ParticipateProgress/ParticipateProgress.tsx
  client/src/types/eventTypes.ts
Labels: feature, 하키

#67 [feature] 이벤트 및 그룹 카드 선택 시 border 유지
  .idea/prettier.xml
  client/src/components/EventGroupSwitcher/EventCard/EventCard.styles.ts
  client/src/components/EventGroupSwitcher/EventCard/EventCard.tsx
  client/src/components/EventGroupSwitcher/GroupCard/GroupCard.styles.ts
  client/src/components/EventGroupSwitcher/GroupCard/GroupCard.tsx
Labels: feature, 하키

#68 [feature] 이벤트/그룹 리스트 페이지 UI 제작
  client/public/images/user.png
  client/src/App.tsx
  client/src/components/EventGroupSwitcher/CreateEventForm/CreateEventForm.tsx
  client/src/components/EventGroupSwitcher/CreateGroupForm/CreateGroupForm.tsx
  client/src/components/EventGroupSwitcher/FormSaveButton/FormSaveButton.tsx
  client/src/components/EventGroupSwitcher/TabSwitcher/TabSwitcher.styles.ts
  client/src/components/EventGroupSwitcher/TabSwitcher/TabSwitcher.tsx
  client/src/components/common/CommonFormLayout/CommonFormLayout.tsx
  client/src/components/common/Header/Header.tsx
  client/src/components/common/Logo/Logo.styles.ts
  client/src/components/common/Logo/Logo.tsx
  client/src/pages/EventGroupSwitcher/EventGroupSwitcher.styles.ts
  client/src/pages/EventGroupSwitcher/EventGroupSwitcher.tsx
Labels: feature, 딜런

#72 [Fix] EventGroupSwitcher-> EventAndGroupList로 페이지명 변경
  client/src/App.tsx
  client/src/components/EventAndGroupList/CreateEventForm/CreateEventForm.tsx
  client/src/components/EventAndGroupList/CreateGroupForm/CreateGroupForm.tsx
  client/src/components/EventAndGroupList/EventCard/EventCard.styles.ts
  client/src/components/EventAndGroupList/EventCard/EventCard.tsx
  client/src/components/EventAndGroupList/EventCardList/EventCardList.styles.ts
  client/src/components/EventAndGroupList/EventCardList/EventCardList.tsx
  client/src/components/EventAndGroupList/EventGroupList/EventGroupList.styles.ts
  client/src/components/EventAndGroupList/EventGroupList/EventGroupList.tsx
  client/src/components/EventAndGroupList/FormSaveButton/FormSaveButton.styles.ts
  client/src/components/EventAndGroupList/FormSaveButton/FormSaveButton.tsx
  client/src/components/EventAndGroupList/GroupCard/GroupCard.styles.ts
  client/src/components/EventAndGroupList/GroupCard/GroupCard.tsx
  client/src/components/EventAndGroupList/ParticipateProgress/ParticipateProgress.styles.ts
  client/src/components/EventAndGroupList/ParticipateProgress/ParticipateProgress.tsx
  client/src/components/EventAndGroupList/TabSwitcher/TabSwitcher.styles.ts
  client/src/components/EventAndGroupList/TabSwitcher/TabSwitcher.tsx
  client/src/components/common/CommonFormLayout/CommonFormLayout.tsx
  client/src/pages/EventAndGroupList/EventAndGroupList.styles.ts
  client/src/pages/EventAndGroupList/EventAndGroupList.tsx
Labels: 딜런, fix

#71 [hotfix] 이벤트 체크인 현황 로드시간 변경
  client/src/hooks/useCheckInEvent.tsx
Labels: hotfix, 하키

#74 [Feature] group detail 페이지 UI 완성
  client/src/api/fileUpload.ts
  client/src/api/loadGroupMemberList.ts
  client/src/api/manualUpload.ts
  client/src/components/GroupDetail/FileUploadModal/FileUploadModal.styles.ts
  client/src/components/GroupDetail/FileUploadModal/FileUploadModal.tsx
  client/src/components/GroupDetail/ManualUploadModal/ManualUploadModal.tsx
  client/src/components/GroupDetail/ManualUploadModal/steps/OptionalStep.styles.ts
  client/src/components/GroupDetail/ManualUploadModal/steps/OptionalStep.tsx
  client/src/components/GroupDetail/ManualUploadModal/steps/RequiredStep.styles.ts
  client/src/components/GroupDetail/ManualUploadModal/steps/RequiredStep.tsx
  client/src/components/GroupDetail/MemberUpdateButton/MemberUpdateButton.tsx
  client/src/components/common/Button/Button.styles.ts
  client/src/components/common/GroupMemberList/GroupMember.tsx
  client/src/components/common/GroupMemberList/GroupMemberList.tsx
  client/src/components/common/ModalFrame/ModalFrame.styles.ts
  client/src/components/common/ModalFrame/ModalFrame.tsx
  client/src/pages/GroupDetail/GroupDetail.styles.ts
  client/src/pages/GroupDetail/GroupDetail.tsx
  client/src/types/studentTypes.ts
Labels: feature, 퓨어

#75 [feature] GroupAndEventList 페이지 이벤트/그룹 생성(수정) 폼 띄우기 완성
  client/src/components/EventAndGroupList/EventCard/EventCard.styles.ts
  client/src/components/EventAndGroupList/EventCard/EventCard.tsx
  client/src/components/EventAndGroupList/EventCardList/EventCardList.tsx
  client/src/components/EventAndGroupList/EventGroupList/EventGroupList.tsx
  client/src/components/EventAndGroupList/GroupCard/GroupCard.styles.ts
  client/src/components/EventAndGroupList/GroupCard/GroupCard.tsx
  client/src/components/EventAndGroupList/GroupCardList/GroupCardList.styles.ts
  client/src/components/EventAndGroupList/GroupCardList/GroupCardList.tsx
  client/src/pages/EventAndGroupList/EventAndGroupList.tsx
  client/src/recoil/currentBandId.ts
  client/src/recoil/currentEventId.ts
Labels: feature, 하키, 딜런, fix

#77 [feature] QR 체크인 화면에 이벤트 데이터 props 로 넘기기
  client/src/components/QrCheckIn/QrScan.tsx
  client/src/components/QrCheckIn/qrCode.styles.ts
  client/src/components/event_detail/CheckInTable/CheckInTable.tsx
  client/src/hooks/useCheckInStudent.tsx
  client/src/pages/EventDetail/EventDetail.tsx
  client/src/pages/QrCheckIn/MainQrCheckIn.styles.ts
  client/src/pages/QrCheckIn/MainQrCheckIn.tsx
Labels: feature, 마이크, fix

#79 [feature] GroupCard, EventCard hover 스타일 적용
  client/src/components/EventAndGroupList/EventCard/EventCard.styles.ts
  client/src/components/EventAndGroupList/GroupCard/GroupCard.styles.ts
Labels: feature, 딜런

#82 [fix] EventAndGroupList Tab 아랫부분 UI 수정
  client/src/components/EventAndGroupList/EventCard/EventCard.styles.ts
  client/src/components/EventAndGroupList/EventCardList/EventCardList.styles.ts
  client/src/components/EventAndGroupList/GroupCard/GroupCard.styles.ts
  client/src/components/EventAndGroupList/GroupCard/GroupCard.tsx
  client/src/components/EventAndGroupList/GroupCardList/GroupCardList.styles.ts
  client/src/components/EventAndGroupList/ParticipateProgress/ParticipateProgress.styles.ts
  client/src/components/common/CommonFormLayout/CommonFormLayout.styles.ts
  client/src/index.css
  client/src/pages/EventAndGroupList/EventAndGroupList.styles.ts
Labels: 하키, 딜런, fix

#84 [fix] : 이미 체크인한 인원 QR 인식 시 노란색 띄우기
  client/src/components/GroupDetail/FileUploadModal/FileUploadModal.tsx
  client/src/components/QrCheckIn/QrScan.tsx
Labels: 마이크, fix
